apps/users/urls.py
from django.urls import path, re_path
from .views import *
from .verify_code import Capcha

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),  # 登录
    path('register/', UserRegisterView.as_view(), name='register'),  # 注册
    path('imagecode', Capcha.as_view(), name='imagecode'),  # 图片验证码
    re_path(r'^changepassword/(?P<token>.*)$', ChangePasswordView.as_view(), name='changepassword'),  # 发送邮箱修改
    path('password/', PasswordSetView.as_view(), name='passwordset'),  # 设置密码
    path('forgetpassword/', ForgetpasswordView.as_view(), name='forgetpassword'),  # 找回密码
    re_path(r'^active/(?P<token>.*)$', UserActiveView.as_view(), name='active'),  # 用户激活
    path('logout/', UserLogoutView.as_view(), name='logout'),  # 退出登录
    path('about/', UserAboutView.as_view(), name='about'),  # 关于
    path('center/', UserCenterView.as_view(), name='center'),  # 个人中心
]

apps/writer/urls.py
from django.urls import re_path, path
from .views import *

urlpatterns = [
    path('', BlogIndexView.as_view(), name='index'),  # 首页
    path('tag/', TagsView.as_view(), name='tags'),  # 标签云
    path('category/', CategoryView.as_view(), name='category'),  # 文章分类
    path('timeline/', TimeLineView.as_view(), name='timeline'),  # 时间线,归档
    path('detail/', DeatilView.as_view(), name='detail'),  # 文章详情信息
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from .settings import MEDIA_ROOT
from django.conf.urls import url

from django.views import static  ##新增
from django.conf import settings  ##新增
from django.conf.urls import url  ##新增

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('apps.users.urls', 'apps.users'), namespace='users')),
    path('', include(('apps.writer.urls', 'apps.writer'), namespace='writer')),
    path('auth/', include(('apps.qauth.urls', 'apps.qauth'), namespace='auth')),
    # 以下代码为设置图片访问路由规则
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    #     第三方登录配置
    url('', include(('social_django.urls', 'social_django'), namespace='social')),
    # 搜索
    path('search/', include(('haystack.urls', 'haystack'), namespace='search')),
    # static
    # url(r'^static/(?P<path>.*)$', static.serve,
    #     {'document_root': settings.STATIC_ROOT}, name='static'),
]
# 404 html
from apps.users import views
handler404 = views.page_not_found

'''
https://github.com/login/oauth/authorize?
client_id=143d93b1d5d93cbf5d420b25ed791cfa0ab55d01&
redirect_uri=http://localhost:8000/complete/github/&
state=btH5H7CudzMLvo1RAz5ooEeFVLXhMFJ9&
response_type=code
'''

apps/writer/models.py
from django.db import models
from mdeditor.fields import MDTextField
from django.utils import timezone
from apps.users.models import User
from db.base_mode import BaseModel


class Article(BaseModel, models.Model):
    auther = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章图片
    picture = models.ImageField(upload_to='picture/%Y%m%d%h', blank=True)
    # 文章标题
    title = models.CharField(max_length=150)
    # markdown 文章正文
    content = MDTextField()
    # 文章摘要
    sumary = models.CharField(max_length=150, blank=False, null=False)
    # 是否置顶
    top = models.BooleanField(default=False)
    total_view = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'tb_article'
        verbose_name = '文章管理'
        verbose_name_plural = verbose_name


class ArticleCategory(models.Model):
    '''文章分栏'''
    title = models.CharField(max_length=150, verbose_name='文章分栏')
    created = models.DateTimeField(default=timezone.now, verbose_name='创建时间')
    # 多对多
    article = models.ManyToManyField(Article)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'tb_category'
        verbose_name = '文章分栏管理'
        verbose_name_plural = verbose_name


class ArticleTags(models.Model):
    '''标签云'''
    title = models.CharField(max_length=150, verbose_name='标签云')
    created = models.DateTimeField(default=timezone.now, verbose_name='创建时间')
    # 多对多
    article = models.ManyToManyField(Article)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'tb_tags'
        verbose_name = '标签云管理'
        verbose_name_plural = verbose_name


class ArticleSwiper(models.Model):
    title = models.CharField(max_length=100)
    # 轮播图
    picture = models.ImageField(upload_to='swiper/%Y%m%d%h', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'tb_swiper'
        verbose_name = '轮播图管理'
        verbose_name_plural = verbose_name


class FriendLink(models.Model):
    title = models.CharField(max_length=150, null=False, unique=True)
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'tb_links'
        verbose_name = '友联管理'
        verbose_name_plural = verbose_name

templates/about.html
{% extends 'base_user.html' %}
{% load static %}
{% block title %}
    about
{% endblock %}

{% block main %}
    <main>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- 主体内容 -->
                    {% load markdown_deux_tags %}

                    <link rel="stylesheet" href="{% static 'css/github.css' %}">
                    <link rel="stylesheet" href="{% static 'css/about.css' %}">

                    <div class="main_content bg-light mt-3 p-3 w-100">
                        <p>{{ user | markdown }}</p>
                    </div>
                    <link rel="stylesheet" href="{% static 'css/top.css' %}">
                    <!--top-->
                    <span class="totop">↑</span>

                </div>
            </div>
        </div>
        <br>
    </main>
{% endblock %}

{% block footer %}
    <footer>
        <div class="card-body text-center px-0 f-14">
            <p class="card-text mb-1">Copyright&nbsp;&copy;&nbsp;<span id="year-info"></span>
                <a href="https://github.com/cat-mz" target="_blank"
                   title="博客作者的Github" style="color: black">CatMz</a>.&nbsp;Powered&nbsp;by&nbsp;Django.
            </p>
            <p class="mb-0">
                <a href="http://beian.miit.gov.cn/" target="_blank"><img class="m-2"
                                                                         src="{% static 'img/01_备案图标.png' %}" alt="">桂公网安备
                    45092302000067号</a>&nbsp;

                <span id="web-day"></span>
            </p>
            <script>function getnewYear() {
                var d = new Date();
                var old = new Date('2021/03/28');
                var x = document.getElementById("year-info");
                x.innerHTML = d.getFullYear();
                var y = document.getElementById("web-day");
                var dd = Math.floor((d.getTime() - old.getTime()) / (24 * 3600 * 1000));
                var d_str = "| 网站已续航 " + dd + " 天";
                y.innerHTML = d_str;
            }

            getnewYear()</script>
        </div>
    </footer>

{% endblock %}

templates/base_user.html
<!DOCTYPE html>
<html lang="zh">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/love.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    {% block link %}

    {% endblock link %}
    <title>  {% block title %}

    {% endblock title %}</title>
    {% block style %}

    {% endblock style %}

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #fff;">
    <!-- LOGO -->
    <a class="navbar-brand" href="{% url 'writer:index' %}"><img src="{% static 'img/catblog.png' %}" alt="catblog"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav  ml-auto" id="mynav">
            <li class="nav-item  mr-2">
                <a class="nav-link" href="{% url 'writer:index' %}"><i class="fa fa-home fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;个人主页</a>
            </li>
            <!--
            <li class="nav-item mr-2">
                <a class="nav-link" href="#"><i class="fa fa-camera-retro"
                                                aria-hidden="true"></i>&nbsp;&nbsp;光影画廊</a>
            </li>
                -->
            <li class="nav-item mr-2">
                <a class="nav-link" href="{% url 'writer:timeline' %}"><i class="fa fa-calendar-check-o"
                                                                          aria-hidden="true"></i>&nbsp;&nbsp;归档日志</a>
            </li>

            <li class="nav-item mr-2">
                <a class="nav-link" href="https://www.github.com/cat-mz" target="_blank"><i class="fa fa-github fa-lg"
                                                                                            aria-hidden="true"></i>&nbsp;&nbsp;项目仓库</a>
            </li>

            <li class="nav-item mr-3">
                <a class="nav-link" href="{% url 'users:about' %}"><i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;自我简述</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="/search">
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" name="q" type="search" placeholder="站内搜索...">
                    <span class="input-group-btn">
                            <button class="btn btn-default btn-outline-success" type="submit"><i class="fa fa-search"
                                                                                                 aria-hidden="true"></i></button>
                        </span>
                </div>
            </div>
        </form>
        <ul class="navbar-nav">
            <div style="display: block;" id="user_Login_register">
                <li class="nav-item float-left">
                    <a class="nav-link" href="{% url 'users:login' %}">登陆</a>
                </li>
                <li class="nav-item float-left">
                    <a class="nav-link" href="{% url 'users:register' %}">注册</a>
                </li>
            </div>
            <li class="nav-item dropdown ml-1" style="display: block;" id="user_center_logout">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span id="u_name"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'users:center' %}">个人中心</a>
                    <a class="dropdown-item" href="{% url 'users:forgetpassword' %}">修改密码</a>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">退出</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<br>

{% block main %}

{% endblock main %}


{% block footer %}
    <footer class="fixed-bottom">
        <div class="card-body text-center px-0 f-14">
            <p class="card-text mb-1">Copyright&nbsp;&copy;&nbsp;<span id="year-info"></span>
                <a href="https://github.com/cat-mz" target="_blank"
                   title="博客作者的Github">CatMz</a>.&nbsp;Powered&nbsp;by&nbsp;Django.
            </p>
            <p class="mb-0">
                <a href="http://beian.miit.gov.cn/" target="_blank"><img class="m-2"
                                                                         src="{% static 'img/01_备案图标.png' %}" alt="">桂公网安备
                    45092302000067号</a>&nbsp;

                <span id="web-day"></span>
            </p>
            <script>function getnewYear() {
                var d = new Date();
                var old = new Date('2021/03/28');
                var x = document.getElementById("year-info");
                x.innerHTML = d.getFullYear();
                var y = document.getElementById("web-day");
                var dd = Math.floor((d.getTime() - old.getTime()) / (24 * 3600 * 1000));
                var d_str = "| 网站已续航 " + dd + " 天";
                y.innerHTML = d_str;
            }

            getnewYear()</script>
        </div>
    </footer>
{% endblock footer %}


</body>

</html>

templates/changepassword.html
{% extends 'base_user.html' %}
{% block title %}
    changepassword
{% endblock %}
{% block style %}
    <style>
        .center_login {
            height: 350px;
            width: 400px;
            background-color: lightgray;
            left: 0;
            right: 0;
            top: 100px;
        }

        .center_title {
            width: 240px;
            height: 160px;
            background-color: lightyellow;
            top: -80px;
            left: 0;
            right: 0;
            font-size: 30px;
        }

        .gradient-text-one {
            background-image: -webkit-linear-gradient(bottom, red, Olive, yellow);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        a {
            color: black;
        }

        h1 {
            color: black;
        }

        h2 {
            width: 300px;
        }
    </style>
{% endblock %}
{% block main %}
    <main>
        <div class="container">
            <div class="row">
                <div class="center_login  m-auto position-relative rounded fixed-bottom">
                    <div class="center_title m-auto position-absolute">
                        <div class="py-4 text-center gradient-text-one text-capitalize">
                            <h1><strong>changepassword</strong></h1>
                            <h1 class="text-center py-5 f-15">欢迎来到CatMz的博客修改密码页面</h1>
                        </div>

                    </div>
                    <div class="center_form  mt-5 ">
                        {% load static %}
                        {% if changepassword %}
                            <form action="{% url 'users:passwordset' %}"
                                  class="text-center py-5 mr-4 change_password"
                                  method="post">
                            {% csrf_token %}
                            <h2 class="text-info ml-5 f-15">请认真并且慎重填写密码，进行修改自身</h2>
                            <div class="form-input mr-2" style="display: block;">
                                <i class="fa fa-key fa-2x  mr-2 mt-4"></i>
                                <input type="password" class="btn bg-light btn-default btn-lg mb-2"
                                       placeholder="请再次输入修改的密码" name="password">
                            </div>
                            <div class="form-input">
                                <button class="btn btn-info mt-4 submit">修改密码</button>
                            </div>
                        {% else %}
                            <script src="{% static 'js/changepassword.js' %}"></script>
                            <form action="{% url 'users:forgetpassword' %}"
                                  class="text-center py-5 mr-4 change_password"
                                  method="post">
                            <h2 class="text-info ml-5 f-15">输入您的用户帐户的验证电子邮件地址，
                                我们将发送给您一个密码重置链接。</h2>
                            <div class="form-input mr-2 mt-3">
                                <i class="fa fa-envelope fa-2x  mr-2 mt-4"></i>
                                <input id="email" type="email" class="btn bg-light btn-default btn-lg mb-2"
                                       placeholder="请输入注册邮箱地址" name="email">
                            </div>
                            <div class="form-input">
                                <button class="btn btn-info mt-4 submit">发送邮件重置密码</button>
                            </div>
                        {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}



templates/login.html
{% extends 'base_user.html' %}
{% load static %}
{% block title %}
    login
{% endblock %}
{% block style %}
    <style>
        .center_login {
            height: 380px;
            width: 300px;
            background-color: lightgray;
            left: 0;
            right: 0;
            top: 100px;
        }

        .center_title {
            width: 240px;
            height: 160px;
            background-color: lightyellow;
            top: -80px;
            left: 0;
            right: 0;
            font-size: 30px;
        }

        .gradient-text-one {
            background-image: -webkit-linear-gradient(bottom, red, Olive, yellow);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        a {
            color: black;
        }

        h1 {
            color: lightgoldenrodyellow;
        }
    </style>
{% endblock %}
{% block main %}
    <main>
        <div class="container">
            <div class="row">
                <div class="center_login  m-auto position-relative rounded fixed-bottom">
                    <div class="center_title m-auto position-absolute">
                        <div class="py-4 text-center gradient-text-one text-capitalize">
                            <h1><strong>login</strong></h1>
                        </div>
                        <div class="text-center mt-2">
                            <a href="{% url 'social:begin' 'github' %}" title="使用github账号登陆"><i class="fa fa-github"
                                                                                                aria-hidden="true"></i></a>
                            <a href="{% url 'social:begin' 'qq' %}" title="使用QQ账号登陆"><i class="fa fa-qq  pr-3 pl-3"
                                                                                        aria-hidden="true"></i></a>
                            <a href="{% url 'social:begin' 'weibo' %}" title="使用WeiBo账号登陆"><i class="fa fa-weibo "
                                                                                              aria-hidden="true"></i></a>
                        </div>
                    </div>
                    <div class="center_form mt-5 ">
                        <h1 class="text-center py-5 f-17">欢迎来到CatMz的博客登陆页面</h1>
                        <form action="{% url 'users:login' %}" class="text-center form-login" method="post">
                            {% csrf_token %}
                            <div class="form-input">
                                <i class="fa fa-user-secret fa-lg mr-2"></i>
                                {% if username %}
                                    <input id="username" type="text" class="btn bg-light btn-default mr-1"
                                           placeholder="请输入用户名"
                                           name="username" value="{{ username }}">
                                {% else %}
                                    <input id="username" type="text" class="btn bg-light btn-default mr-1"
                                           placeholder="请输入用户名"
                                           name="username">
                                {% endif %}
                            </div>
                            <div class="form-input mr-2">
                                <i class="fa fa-key fa-lg  mr-2 mt-4"></i>
                                <input id="password" type="password" class="btn bg-light btn-default"
                                       placeholder="请输入密码"
                                       name="password">
                            </div>
                            <div class="form-input  mr-2 mt-2 text-left ml-5 ">
                                {% if checked %}
                                    <input value="on" name="btn" id="btn" type="checkbox"
                                           class="btn bg-light btn-default">
                                    <label for="btn">记住密码</label>
                                {% else %}
                                    <input name="btn" id="btn" type="checkbox"
                                           class="btn bg-light btn-default">
                                    <label for="btn">记住密码</label>
                                {% endif %}
                            </div>
                            <div class="form-input">
                                <button class="btn btn-info mt-1 submit">登陆</button>
                            </div>
                        </form>
                        <ul>
                            <li class="float-left ml-3 "><a href="{% url 'users:forgetpassword' %}">忘记密码</a></li>
                            <li class="float-right mr-3 "><a href="{% url 'users:register' %}">注册页面</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}


templates/register.html
{% extends 'base_user.html' %}
{% load static %}
{% block title %}
    register
{% endblock %}
{% block style %}
    <style>
        .center_login {
            height: 500px;
            width: 600px;
            background-color: lightgray;
            left: 0;
            right: 0;
            top: 80px;
        }

        .center_title {
            width: 240px;
            height: 160px;
            background-color: lightyellow;
            top: -80px;
            left: 0;
            right: 0;
            font-size: 30px;
        }

        .gradient-text-one {
            background-image: -webkit-linear-gradient(bottom, red, Olive, yellow);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        a {
            color: black;
        }

        h1 {
            color: black;
        }
    </style>
{% endblock %}

{% block main %}
    <main>
        <div class="container">
            <div class="row">
                <div class="center_login  m-auto position-relative rounded fixed-bottom">
                    <div class="center_title m-auto position-absolute">
                        <div class="py-4 text-center gradient-text-one text-capitalize">
                            <h1><strong>register</strong></h1>
                            <h1 class="text-center py-5 f-17">欢迎来到CatMz的博客注册页面</h1>
                        </div>


                    </div>
                    <div class="center_form py-5 mt-5 ">
                        <script src="{% static 'js/register.js' %}"></script>
                        <form action="{% url 'users:register' %}" method="post" class="text-center ml-3 form-register">
                            {% csrf_token %}
                            <div class="form-input">
                                <i class="fa fa-user-secret fa-lg mr-2"></i>
                                <input type="text" class="btn bg-light btn-default mr-1" placeholder="请输入用户名"
                                       name="username" id="username">
                                <a href="" class="ml-3 invisible"><img src="{% static 'img/code.jpg' %}"
                                                                       class="w-25"></a>
                            </div>
                            <div class="form-input mr-2">

                                <i class="fa fa-key fa-lg  mr-2 mt-4"></i>
                                <input type="password" class="btn bg-light btn-default" placeholder="请输入密码"
                                       name="password" id="password">
                                <a href="" class="ml-3 invisible"><img src="{% static 'img/code.jpg' %}"
                                                                       class="w-25"></a>
                            </div>
                            <div class="form-input mr-2">
                                <i class="fa fa-key fa-lg mr-2 mt-4"></i>
                                <input type="password" class="btn bg-light btn-default" id="password2" name="password2"
                                       placeholder="请再次输入密码">
                                <a href="" class="ml-3 invisible"><img src="{% static 'img/code.jpg' %}"
                                                                       class="w-25"></a>
                            </div>
                            <div class="form-input">
                                <i class="fa fa-envelope fa-lg mr-2 mt-4"></i>
                                <input type="email" class="btn bg-light btn-default mr-2" id="email" name="email"
                                       placeholder="请填写正确的邮箱信息">
                                <a href="" class="ml-3 invisible"><img src="{% static 'img/code.jpg' %}"
                                                                       class="w-25"></a>
                            </div>
                            <div class="form-input">
                                <input type="text" hidden name="uuid" id="uuuid">
                                <i class="fa fa-file-code-o fa-lg mr-2 mt-4"></i>
                                <input type="text" class="btn bg-light btn-default mr-2" id="code" name="code"
                                       placeholder="请填写图片验证码">
                                <a href="javascript:;" class="ml-3 code"><img id="code_img" src=""
                                                                              class="w-25"></a>
                            </div>
                            <div class="form-input">
                                <button class="btn btn-info mt-4">注册</button>
                            </div>
                        </form>
                        <ul class="mr-4 ml-4">
                            <li class="float-left ml-3 "><a href="{% url 'users:forgetpassword' %}">忘记密码</a></li>
                            <li class="float-right mr-3 "><a href="{% url 'users:login' %}">登陆页面</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}



templates/tags.html
{% extends 'base_user.html' %}
{% load static %}
{% block title %}
    article
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block main %}
    <main>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- 主体内容 -->
                    <ul class="main_content">
                        {% for article in articles %}
                            <li class="media mb-1 p-2 bg-light  mb-sm-2 p-lg-3">
                                <div class="align-self-center mr-2 mr-lg-3 w-25 modal-open">
                                    <a href="/detail?id={{ article.id }}">
                                        <img class="w-100 article-img" src="{{ article.picture.url }}"
                                             alt="{{ article.title }}">
                                    </a>
                                </div>
                                <div class="media-body">
                                    {% if article.top %}
                                        <img class="float-right top-article-img" src="{% static 'img/top.png' %}">
                                    {% endif %}
                                    <div class="text-muted mb-2 f-12">


                                        <img class="avatar" src="{{ article.auther.avatar.url }}"
                                             alt="{{ article.auther.username }}">

                                        <span>{{ article.auther.username }}</span>
                                        <span><i class="fa fa-calendar-times-o ml-2 mr-1"></i>{{ article.create_time }}</span>
                                    </div>
                                    <h2 class="mt-0 font-weight-bold text-info f-color f-17">
                                        <a href="/detail?id={{ article.id }}"
                                           class="f-color">{{ article.title }}</a>
                                    </h2>
                                    <p class="d-none d-sm-block mb-2 f-15 py-1">{{ article.sumary }}</p>
                                    <div class="text-muted mb-0 f-12">
                                        <a class="f-category" href="/category/{{ article.articletags_set.first }}/"
                                           title="查看当前分类下更多文章">
                                            <i class="fa fa-book mr-1"></i>{{ article.articletags_set.first }}</a>
                                        <span><i class="fa fa-eye ml-2 mr-1"></i>{{ article.total_view }}</span>
                                        <span><i class="fa fa-comments ml-2 mr-1"></i>{{ article.comment_count }}</span>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}

                    </ul>
                    <div class="text-center mt-2 mt-sm-1 mt-md-0 mb-3 f-16">
                        {% if page.has_previous %}
                            <!--判断是否为第二页,第二页直接请求首页,避免url携带page-->
                            {% if page.previous_page_number == 1 %}
                                <a class="text-success" href="{% url 'writer:index' %}">上一页</a>
                            {% else %}
                                <a class="text-success" href="?page={{ page.previous_page_number }}">上一页</a>
                            {% endif %}
                        {% else %}
                            <span class="text-secondary" title="当前页已经是首页">上一页</span>
                        {% endif %}


                        <span class="mx-2">第&nbsp;{{ page.number }}&nbsp;/&nbsp;{{ page_total }}&nbsp;页</span>
                        {% if page.has_next %}
                            <a class="text-success" href="?page={{ page.next_page_number }}">下一页</a>
                        {% else %}
                            <span class="text-secondary" title="当前页已经是为最后一页">下一页</span>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}